name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildSdk:
    name: Build SDK
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/centeredge/yardarm:0.1.0-alpha009
      options: --user root:root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: "5.7.0"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: true
          configFilePath: "GitVersion.yml"

      - name: Set Version
        run: sed -i 's/0.0.0-replace/${{ steps.gitversion.outputs.legacySemVerPadded }}/g' swagger.json

      - name: Build
        run: yardarm generate -i ./swagger.json --nupkg ./dist/ -n CenterEdge.TextPay.Api -v ${{ steps.gitversion.outputs.nuGetVersionV2 }} -x Newtonsoft.Json --repository-url https://github.com/${GITHUB_REPOSITORY}.git --repository-commit ${GITHUB_SHA}

      - name: Push
        working-directory: ./dist
        # Publish CI packages from PRs and releases to the main brach
        run: >-
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/CenterEdge/index.json
          && dotnet nuget push **/*.${{ steps.gitversion.outputs.nuGetVersionV2 }}.nupkg -k ${{ secrets.GITHUB_TOKEN  }} -s github
